#!/bin/sh
#
# Usage:
#
#   pin-release-image PATH PULLSPEC
#
# edits the openshift-install executable at PATH in place to replace
# the default release pullspec with the user-provided PULLSPEC.

set -e

OPENSHIFT_INSTALL="${1}"
RELEASE_IMAGE="${2}"
DEFAULT_RELEASE_IMAGE='registry.svc.ci.openshift.org/openshift/origin-release:v4.0'
DEFAULT_PADDING='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

MAX_LENGTH="$((${#DEFAULT_RELEASE_IMAGE} + ${#DEFAULT_PADDING}))"
PADDING_COUNT="$((${MAX_LENGTH} - ${#RELEASE_IMAGE}))"
if test 0 -gt "${PADDING_COUNT}"
then
	printf 'release image is %d characters long, but the limit is %d\n' "${#RELEASE_IMAGE}" "${MAX_LENGTH}" >&2
	exit 1
fi

PADDING=''
while test "${PADDING_COUNT}" -gt "${#PADDING}"
do
	PADDING="${PADDING}X"
done

exec sed -i "s|${DEFAULT_RELEASE_IMAGE}\\x0${DEFAULT_PADDING}|${RELEASE_IMAGE}\\x0${PADDING}|" "${OPENSHIFT_INSTALL}"
