#!/bin/sh

./s3-buckets &&
./instances &&
./autoscaling-groups &&
./load-balancers &&
./iam-instance-profiles &&
./iam-roles &&
./nat-gateways &&
./network-interfaces &&
./elastic-ips &&
./security-groups &&
./vpcs
