#!/bin/sh

IDS="$(aws autoscaling describe-auto-scaling-groups | jq -r '.AutoScalingGroups[] | select(now - (.CreatedTime | sub("[.][0-9]*"; "") | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | .AutoScalingGroupName')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "removing $(echo "${IDS}" | wc -w) autoscaling groups over four hours old" &&
sleep 3 &&
ec=0 &&
for ID in ${IDS}
do
	aws autoscaling delete-auto-scaling-group --auto-scaling-group-name "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
