#!/bin/sh

IDS="$(aws ec2 describe-addresses | jq -r '.Addresses[] | select(.AssociationId == null) | .AllocationId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "waiting for an hour before removing $(echo "${IDS}" | wc -w) elastic IP(s)" &&
sleep 3600 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 release-address --allocation-id "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
