#!/bin/sh

# Apparently there is no way to delete these using .InstanceProfileId?
DATA="$(aws iam list-instance-profiles | jq '[.InstanceProfiles[] | select(.InstanceProfileName | startswith("ci-op-")) | select(now - (.CreateDate | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | {id: .InstanceProfileName, roles: ([.Roles[] | .RoleName])}]')" &&
IDS="$(echo "${DATA}" | jq -r '.[] | .id')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "removing $(echo "${IDS}" | wc -w) cluster IAM instance profiles over four hours old" &&
sleep 3 &&
ec=0 &&
for ID in ${IDS}
do
	ROLES="$(echo "${DATA}" | jq -r ".[] | select(.id == \"${ID}\") | .roles[]")" &&
	if test -n "${ROLES}"
	then
		echo "removing $(echo "${ROLES}" | wc -w) roles from instance profile ${ID}" &&
		ecr=0 &&
		for ROLE in ${ROLES}
		do
			aws iam remove-role-from-instance-profile --instance-profile-name "${ID}" --role-name "${ROLE}" ||
			ecr=1  # store a non-zero exit-code, but keep going
		done &&
		if test "${ecr}" -ne 0
		then
			ec=1 &&
			continue  # avoid: An error occurred (DeleteConflict) when calling the DeleteInstanceProfile operation: Cannot delete entity, must remove roles from instance profile first.
		fi
	fi &&
	aws iam delete-instance-profile --instance-profile-name "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
