#!/bin/sh

IDS="$(aws ec2 describe-instances | jq -r '.Reservations[] | .Instances[] | select(.State.Name != "terminated") | select(now - (.LaunchTime | sub("[.][0-9]*"; "") | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | .InstanceId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "removing $(echo "${IDS}" | wc -w) instances over four hours old" &&
sleep 3 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 terminate-instances --instance-ids "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
