#!/bin/sh

NAMES="$(aws elb describe-load-balancers | jq -r '.LoadBalancerDescriptions[] | select(now - (.CreatedTime | sub("[.][0-9]*"; "") | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | .LoadBalancerName')" &&
if test -z "${NAMES}"
then
	exit 0
fi &&
echo "removing $(echo "${NAMES}" | wc -w) load balancers over four hours old" &&
sleep 3 &&
ec=0 &&
for NAME in ${NAMES}
do
	aws elb delete-load-balancer --load-balancer-name "${NAME}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
