#!/bin/sh

IDS="$(aws ec2 describe-nat-gateways | jq -r '.NatGateways[] | select(now - (.CreateTime | sub("[.][0-9]*"; "") | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | .NatGatewayId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "removing $(echo "${IDS}" | wc -w) NAT gateways over four hours old" &&
sleep 3 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 delete-nat-gateway --nat-gateway-id "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
