#!/bin/sh
#
# Run nat-gateways first to avoid errors like:
#
#   An error occurred (DependencyViolation) when calling the DeleteSecurityGroup operation: resource sg-075e29b6d10ce7c1a has a dependent object

IDS="$(aws ec2 describe-network-interfaces | jq -r '.NetworkInterfaces[] | .NetworkInterfaceId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "waiting for an hour before removing $(echo "${IDS}" | wc -w) network interfaces" &&
sleep 3600 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 delete-network-interface --network-interface-id "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
