#!/bin/sh

IDS="$(aws s3api list-buckets | jq -r '.Buckets[] | select(now - (.CreationDate | sub("[.][0-9]*"; "") | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime) > 4*60*60) | .Name')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "removing $(echo "${IDS}" | wc -w) s3 buckets over 4 hours old" &&
sleep 3 &&
ec=0 &&
for ID in ${IDS}
do
	aws s3 rm "s3://${ID}" --recursive &&
	aws s3api delete-bucket --bucket "${ID}" &&
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
