#!/bin/sh

# Filter out default security groups to avoid:
#
#   An error occurred (CannotDelete) when calling the DeleteSecurityGroup operation: the specified group: "sg-0809c4631a482761e" name: "default" cannot be deleted by a user
IDS="$(aws ec2 describe-security-groups | jq -r '.SecurityGroups[] | select(.GroupName != "default") | .GroupId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "waiting for an hour before removing $(echo "${IDS}" | wc -w) security groups" &&
sleep 3600 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 delete-security-group --group-id "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
