#!/bin/sh

IDS="$(aws ec2 describe-vpcs | jq -r '.Vpcs[] | .VpcId')" &&
if test -z "${IDS}"
then
	exit 0
fi &&
echo "waiting for an hour before removing $(echo "${IDS}" | wc -w) virtual private clouds" &&
sleep 3600 &&
ec=0 &&
for ID in ${IDS}
do
	aws ec2 delete-vpc --vpc-id "${ID}" ||
	ec=1  # store a non-zero exit-code, but keep going
done &&
exit "${ec}"
